// Generated by CoffeeScript 1.10.0
(function() {
  $.fn.extend({
    somePlugin: function(options) {
      var settings;
      settings = {
        option1: "red"
      };
      settings = $.extend(settings, options);
      return this.each(function() {
        return $(this).css({
          color: settings.color
        });
      });
    }
  });

}).call(this);
